### PR TITLE
Fix e2e by removing temporary fixed version of clusteradm and installing latest clusteradm at runtime

### PR DESCRIPTION
**Pull request by mikeshng**
# Description of the change(s):
* Undo the fixed version clusteradm workaround. Build the latest clusteradm at e2e runtime.

## Why do we need this PR:
*  Undo workaround fix in e2e

## Issue reference: 
* NA

## Test API/Unit - Success
```script
NA
```

### CODE REVIEW

**Review by rokej — APPROVED** [review]
Thank you @mikeshng

**Comment by mikeshng** [comment]
needs https://github.com/openshift/release/pull/36672 to be merged.

**Comment by mikeshng** [comment]
@rokej please review again thanks. I added the `clusteradm` folder as one of the git ignore.

**Pull request merged**
