### PR TITLE
Delete bucket namespace flag

### PR DESCRIPTION
**Pull request by zhujian7**
The bucket secret namespace **must** be the clusterName namespace, otherwise, the agent getting the secret will fail(permission problem, the permission manifest just grant the agent getting secret in the clusterName namespace)

### CODE REVIEW

**Comment by ianzhang366** [comment]
Now the buckect secret is expecting to be placed at `open-cluster-management` namespace, which is the addon-manager's namespace.

https://github.com/stolostron/hypershift-addon-operator/blob/acd2b808146b90d6327e00c2151c1f6b4d96eddf/pkg/util/constant.go#L11-L12

which will reduce the secret duplication of the bucket secrets, what do you think?

**Comment by zhujian7** [comment]
> which will reduce the secret duplication of the bucket secrets, what do you think?

@ianzhang366 That means all managed clusters turning to a hypershift management cluster will use the same s3 bucket? I am not quite sure that is what we want.

**Review by ianzhang366 — APPROVED** [review]

**Pull request merged**
